/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com__0of_adapters_services_impl_NetworkServiceImpl_NativeEstablishProxyListener */

#ifndef _Included_com__0of_adapters_services_impl_NetworkServiceImpl_NativeEstablishProxyListener
#define _Included_com__0of_adapters_services_impl_NetworkServiceImpl_NativeEstablishProxyListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
