/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com__0of_adapters_UIMessageHandler */

#ifndef _Included_com__0of_adapters_UIMessageHandler
#define _Included_com__0of_adapters_UIMessageHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com__0of_adapters_UIMessageHandler
 * Method:    _onMessageHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com__0of_adapters_UIMessageHandler__1onMessageHandle
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
