/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com__0of_adapters_JContext */

#ifndef _Included_com__0of_adapters_JContext
#define _Included_com__0of_adapters_JContext
#ifdef __cplusplus
extern "C" {
#endif
#undef com__0of_adapters_JContext_NULL
#define com__0of_adapters_JContext_NULL 0i64
/*
 * Class:     com__0of_adapters_JContext
 * Method:    _freeHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com__0of_adapters_JContext__1freeHandler
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com__0of_adapters_JContext
 * Method:    _instantiateService
 * Signature: (Ljava/lang/String;J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com__0of_adapters_JContext__1instantiateService
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
