/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com__0of_adapters_NativeAppContext */

#ifndef _Included_com__0of_adapters_NativeAppContext
#define _Included_com__0of_adapters_NativeAppContext
#ifdef __cplusplus
extern "C" {
#endif
#undef com__0of_adapters_NativeAppContext_NULL
#define com__0of_adapters_NativeAppContext_NULL 0i64
/*
 * Class:     com__0of_adapters_NativeAppContext
 * Method:    getFromNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com__0of_adapters_NativeAppContext_getFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com__0of_adapters_NativeAppContext
 * Method:    _start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com__0of_adapters_NativeAppContext__1start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com__0of_adapters_NativeAppContext
 * Method:    _quit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com__0of_adapters_NativeAppContext__1quit
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
